### ISSUE TITLE
Flag arguments causes `poweroff` to crash and invert text color

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/coreutils#3]
![Screenshot_20220421_225859](https://user-images.githubusercontent.com/25323231/164502198-c1e8fc6a-7222-4b82-a16b-b1a144e81693.png)

**Comment by Ocawesome101** [comment]
Oops. Won't be able to fix right away but this issue is on line 35 - `args` should be `argv`

**Comment by atirutw** [comment]
Fixed in b95dd2bb8dbf971815859c6ae53ebd2d259c3401
